global:
  scrape_interval:     10s

scrape_configs:
  - job_name: 'commentsService'
    static_configs:
      - targets:
        - host.docker.internal:9100

  - job_name: 'moderationService'
    static_configs:
      - targets:
        - host.docker.internal:9101

  - job_name: 'notificationService'
    static_configs:
      - targets:
        - host.docker.internal:9102
